### PR TITLE
Update git ignore

### PR DESCRIPTION
**Pull request by SamIAmHarris**
@dazza5000 I added a good amount of stuff in there. I hope it doesn't break your local build. When I pulled down the project yesterday it was not building because it was trying to find the flutter sdk on your machine.

### CODE REVIEW

**Comment by dazza5000** [comment]
Testing locally

**Comment by dazza5000** [comment]
Sam is trying to sabotage me

**Comment by SamIAmHarris** [comment]
Took out too many iOS files from .gitignore

**Comment by dazza5000** [comment]
Retrying shortly. Thank you!

**Pull request closed without merging**
